version: "3.9"
services:
  redis:
    image: "redis:alpine"
    container_name: "yafree-redis"
#    ports:
#      - "6379:6379"

  js_api:
    image: "yafree-js-api"
    container_name: "yafree-js-api"
    build:
      dockerfile: "Docker.JS_API.Dockerfile"
#    ports:
#      - "6666:6666"

  web:
    image: "yafree-web"
    container_name: "yafree-web"
    build:
      dockerfile: Docker.Web.Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - "./db/:/db"
    depends_on:
      - redis
      - js_api
#    network_mode: "bridge"
