from django.urls import path
from . import views

urlpatterns = [
    path(
        '',
        views.IndexView.as_view(),
        name="ton-index"
    ),
    path(
        'somethingwentwrong/',
        views.SomethingWentWrongView.as_view(),
        name="ton-something-went-wrong"
    ),
    path(
        'signtx/',
        views.SignTxView,
        name="ton-sign-tx"
    ),

    path(
        'contract/make_deal/new',
        views.NewMakeDealContractView,
        name="ton-new-make-deal-contract"
    ),
    path(
        'contract/make_deal/new/preview',
        views.NewMakeDealContractPreviewView,
        name="ton-new-make-deal-contract-preview"
    ),
    path(
        'contract/make_deal/info/<int:pk>',
        views.MakeDealContractInfoView,
        name="ton-make-deal-contract-info"
    ),
    path(
        'contract/make_deal/respond/<int:pk>/',
        views.MakeDealContractRespondView,
        name="ton-respond-to-make-deal-contract"
    ),
    path(
        'contract/make_deal/acceptinvitation/<int:pk>',
        views.MakeDealContractAcceptInvitationView,
        name="ton-accept-invitation"
    ),

    path(
        'contract/execution/info/<int:pk>',
        views.ExecutionContractInfoView,
        name="ton-execution-contract-info"
    ),
    path(
        'contract/execution/finishexecution/<int:pk>',
        views.FinishExecutionView,
        name="ton-finish-execution"
    ),
    path(
        'contract/execution/addsolution/<int:pk>',
        views.AddSolutionView,
        name="ton-add-solution"
    ),
    path(
        'contract/execution/addexecutiontime/<int:pk>',
        views.AddExecutionTimeView,
        name="ton-add-execution-time"
    ),
    path(
        'contract/execution/acceptsolution/<int:pk>',
        views.AcceptSolutionView,
        name="ton-accept-solution"
    ),
    path(
        'contract/execution/declinesolution/<int:pk>',
        views.DeclineSolutionView,
        name="ton-decline-solution"
    ),

    path(
        'contract/judgment/info/<int:pk>',
        views.JudgmentContractInfoView,
        name="ton-judgment-contract-info"
    ),
    path(
        'contract/judgment/addargument/<int:pk>',
        views.AddArgumentView,
        name="ton-add-argument"
    ),
    path(
        'contract/judgment/votefor/<int:pk>',
        views.VoteForView,
        name="ton-vote-for"
    ),

    path(
        'me',
        views.MeView,
        name="ton-me"
    ),
    path(
        'me/ownedmakedealcontracts',
        views.OwnedMakeDealContractsView,
        name="ton-owned-make-deal-contracts"
    ),
    path(
        'me/ownewexecutioncontracts',
        views.OwnedExecutionContractsView,
        name="ton-owned-execution-contracts"
    ),
    path(
        'me/ownedjudgmentcontracts',
        views.OwnedJudgmentContractsView,
        name="ton-owned-judgment-contracts"
    ),
    path(
        'me/iexecute',
        views.IExecuteView,
        name="ton-i-execute"
    ),
    path(
        'me/ijudge',
        views.IJudgeView,
        name="ton-i-judge"
    ),

    path(
        'actual/makedeal',
        views.ActualMakeDealContractsView,
        name="ton-actual-make-deal-contracts"
    ),
    path(
        'actual/judgment',
        views.ActualJudgmentContractsView,
        name="ton-actual-judgment-contracts"
    ),
]
