# Generated by Django 4.1.7 on 2023-03-14 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ton', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=42)),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ton.marketplaceuser')),
            ],
        ),
        migrations.CreateModel(
            name='MakeDealContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=42)),
                ('task_info_contract_address', models.CharField(max_length=42)),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ton.marketplaceuser')),
            ],
        ),
        migrations.CreateModel(
            name='JudgmentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=42)),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('execution_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eth.executioncontract')),
            ],
        ),
        migrations.AddField(
            model_name='executioncontract',
            name='make_deal_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eth.makedealcontract'),
        ),
    ]
