# Generated by Django 4.2 on 2023-05-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ton', '0001_initial'),
        ('eth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eth.makedealcontract')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ton.marketplaceuser')),
            ],
        ),
    ]
